/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "2ac50e7249fbd55e6f517a28131605c9fb9fe897"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
