/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "2ba93af511033c75c55cac08672b808e2c3fbe71"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
