/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "bf2d9e02d58ea01f1c239f7e2fc024cba140ccb1"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
