/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "7d479192f0bf2a2f0e872d40e3fe3ce9978bf3cc-"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
